-- Dữ liệu gốc Anyhome — sinh tự động bởi scripts/generate-seed.ts, đừng sửa tay.
-- Chạy SAU supabase/schema.sql. Chạy lại sẽ ghi đè các bản ghi mẫu (theo id).

begin;

insert into public.projects (id, slug, title, category, location, scale, area, year, client, scope, summary, cover, gallery, before_after, featured, status, created_at) values
  ('prj-001', 'nha-may-ma-kem-cong-ty-van-xuan', 'Nhà máy mạ kẽm Công ty Vạn Xuân', 'industrial', 'CCN Vạn Xuân, Tam Nông, Phú Thọ', 'Khung thép tiền chế · 6.500 m²', 6500, 2024, 'Công ty Vạn Xuân', array['Thiết kế', 'Thi công']::text[], 'Nhà máy mạ kẽm nhúng nóng với kết cấu khung thép tiền chế khẩu độ lớn, hệ thống thông gió và xử lý khí thải chuyên dụng.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/12.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/12.jpg']::text[], null, true, 'published', '2024-06-01T00:00:00.000Z'),
  ('prj-002', 'nha-may-cong-ty-che-tao-bom-hai-duong', 'Nhà máy Công ty Chế tạo Bơm Hải Dương', 'industrial', 'Đường Ngô Quyền, TP. Hải Dương', 'Nhà xưởng + nhà ăn · 4.200 m²', 4200, 2023, 'Công ty CP Chế tạo Bơm Hải Dương', array['Thiết kế', 'Thi công']::text[], 'Cải tạo, mở rộng nhà xưởng sản xuất và thiết kế – thi công hạng mục nhà ăn cho cán bộ công nhân viên.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/logo.png', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/logo.png']::text[], null, false, 'draft', '2023-06-02T00:00:00.000Z'),
  ('prj-003', 'nha-xuong-san-xuat-cho-thue-xuan-phuong', 'Nhà xưởng sản xuất & cho thuê Xuân Phương', 'industrial', 'CCN Đan Phượng giai đoạn 2, Hà Nội', 'Cụm nhà xưởng · 8.000 m²', 8000, 2024, 'Công ty Xuân Phương', array['Thiết kế', 'Thi công']::text[], 'Cụm nhà xưởng tiêu chuẩn phục vụ sản xuất và cho thuê, tối ưu khẩu độ, chiếu sáng tự nhiên và phòng cháy chữa cháy.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/13.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/13.jpg']::text[], null, false, 'published', '2024-06-03T00:00:00.000Z'),
  ('prj-004', 'nha-may-cong-ty-tnhh-anh-sang-tien-du', 'Nhà máy Công ty TNHH Ánh sáng Tiến Dư', 'industrial', 'Xã Bình Minh, Thanh Oai, Hà Nội', 'Nhà máy + văn phòng · 5.100 m²', 5100, 2023, 'Công ty TNHH Ánh sáng Tiến Dư', array['Thiết kế', 'Thi công']::text[], 'Thiết kế và thi công trọn gói nhà máy sản xuất thiết bị chiếu sáng cùng khối văn phòng điều hành.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/17.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/17.jpg']::text[], null, false, 'published', '2023-06-04T00:00:00.000Z'),
  ('prj-005', 'nha-may-san-xuat-thiet-bi-cong-nghiep-kintop', 'Nhà máy sản xuất thiết bị công nghiệp Kintop', 'industrial', 'KCN Lai Cách, Cẩm Giàng, Hải Dương', 'Nhà xưởng · 7.200 m²', 7200, 2025, 'Công ty Kintop', array['Thiết kế', 'Thi công']::text[], 'Nhà máy sản xuất thiết bị công nghiệp, kết cấu thép kết hợp bê tông cốt thép, cầu trục 10 tấn.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/15.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/15.jpg']::text[], null, true, 'published', '2025-06-05T00:00:00.000Z'),
  ('prj-006', 'nha-may-nhom-kinh-cong-ty-cp-hcc', 'Nhà máy nhôm kính Công ty CP HCC', 'industrial', 'CCN Thanh Đa, Phúc Thọ, Hà Nội', 'Nhà xưởng · 5.600 m²', 5600, 2024, 'Công ty CP Nhôm kính HCC', array['Thiết kế', 'Thi công']::text[], 'Nhà máy gia công nhôm kính với dây chuyền khép kín, mặt bằng bố trí theo luồng sản xuất một chiều.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/14.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/14.jpg']::text[], null, false, 'published', '2024-06-06T00:00:00.000Z'),
  ('prj-007', 'showroom-o-to-vinfast-vinh-yen', 'Showroom ô tô VinFast Vĩnh Yên', 'industrial', 'TP. Vĩnh Yên, Vĩnh Phúc', 'Showroom 3S · 2.400 m²', 2400, 2023, 'Đại lý VinFast Vĩnh Yên', array['Thi công']::text[], 'Thi công showroom – xưởng dịch vụ theo bộ nhận diện tiêu chuẩn của thương hiệu.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/05.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/05.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/03.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/04.jpg']::text[], null, false, 'published', '2023-06-07T00:00:00.000Z'),
  ('prj-008', 'nha-may-ming-shin-hung-yen', 'Nhà máy MING SHIN Hưng Yên', 'industrial', 'Hưng Yên', 'Nhà xưởng · 9.000 m²', 9000, 2025, 'MING SHIN', array['Thi công', 'Giám sát']::text[], 'Nhà máy vốn FDI, thi công kết cấu thép khẩu độ lớn và hệ thống kỹ thuật MEP đồng bộ.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/11.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/11.jpg']::text[], null, false, 'published', '2025-06-08T00:00:00.000Z'),
  ('prj-009', 'biet-thu-dia-trung-hai', 'Biệt thự Địa Trung Hải', 'residential', 'Thanh Hóa', '3 tầng · 520 m² sàn', 520, 2024, null, array['Thiết kế', 'Thi công']::text[], 'Biệt thự phong cách Địa Trung Hải với mái ngói đỏ, vòm cong và sân vườn bao quanh.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/55.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/55.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/56.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/51.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/49.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/50.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/52.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/53.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/54.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/48.jpg']::text[], null, true, 'published', '2024-06-09T00:00:00.000Z'),
  ('prj-010', 'biet-thu-mai-nhat', 'Biệt thự mái Nhật', 'residential', 'Hòa Bình', '2 tầng · 380 m² sàn', 380, 2023, null, array['Thiết kế', 'Thi công']::text[], 'Biệt thự nghỉ dưỡng mái Nhật, hòa vào cảnh quan đồi núi với vật liệu gỗ và đá tự nhiên.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/07.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/07.jpg']::text[], null, true, 'published', '2023-06-10T00:00:00.000Z'),
  ('prj-011', 'biet-thu-kdt-thanh-pho-giao-luu', 'Biệt thự KĐT Thành phố Giao Lưu', 'residential', 'KĐT Thành phố Giao Lưu, Bắc Từ Liêm, Hà Nội', '4 tầng · 600 m² sàn', 600, 2024, null, array['Thiết kế', 'Thi công']::text[], 'Biệt thự hiện đại với mặt đứng kính lớn, giếng trời trung tâm và tầng hầm để xe.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/18.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/18.jpg']::text[], null, true, 'published', '2024-06-11T00:00:00.000Z'),
  ('prj-012', 'biet-thu-gia-dinh-hac-thanh', 'Biệt thự gia đình Hạc Thành', 'residential', 'Phường Hạc Thành, Thanh Hóa', '3 tầng · 450 m² sàn', 450, 2025, null, array['Thiết kế', 'Thi công']::text[], 'Biệt thự tân cổ điển cho gia đình ba thế hệ, công năng tách bạch và sân vườn riêng.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/08.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/08.jpg']::text[], null, false, 'published', '2025-06-12T00:00:00.000Z'),
  ('prj-013', 'khach-san-song-hong', 'Khách sạn Sông Hồng', 'residential', 'Vĩnh Phúc', '9 tầng · 4.800 m² sàn', 4800, 2022, null, array['Thiết kế']::text[], 'Khách sạn 3 sao với sảnh đón thông tầng, nhà hàng và 60 phòng nghỉ.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/63.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/63.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/62.jpg']::text[], null, false, 'published', '2022-06-13T00:00:00.000Z'),
  ('prj-014', 'van-phong-7-tang-bach-dang', 'Văn phòng 7 tầng Bạch Đằng', 'residential', 'Phường Bạch Đằng, TP. Hạ Long', '7 tầng · 1.750 m² sàn', 1750, 2024, null, array['Thiết kế']::text[], 'Tòa văn phòng mặt tiền kính hướng biển, kết cấu khung BTCT kết hợp lam chắn nắng.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/58.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/58.jpg']::text[], null, false, 'published', '2024-06-14T00:00:00.000Z'),
  ('prj-015', 'truong-cao-dang-thuong-mai', 'Trường Cao đẳng Thương mại', 'residential', 'TP. Đà Nẵng', 'Khối giảng đường · 6.000 m² sàn', 6000, 2022, null, array['Thiết kế']::text[], 'Khối giảng đường và thư viện với hành lang thông gió tự nhiên phù hợp khí hậu miền Trung.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/06.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/06.jpg']::text[], null, false, 'published', '2022-06-15T00:00:00.000Z'),
  ('prj-016', 'ket-cau-thep-chung-cu-five-star-garden', 'Kết cấu thép chung cư Five Star Garden', 'residential', 'Số 2 Kim Giang, Hà Nội', 'Hạng mục kết cấu thép', 3000, 2025, null, array['Thiết kế', 'Thi công']::text[], 'Thiết kế và thi công hạng mục kết cấu thép cho tổ hợp chung cư cao tầng.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/69.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/69.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/61.jpg']::text[], null, false, 'published', '2025-06-16T00:00:00.000Z'),
  ('prj-017', 'chung-cu-mini-thach-ban', 'Chung cư mini Thạch Bàn', 'residential', 'Thạch Bàn, Long Biên, Hà Nội', '8 tầng · 1.400 m² sàn', 1400, 2023, null, array['Thiết kế', 'Thi công']::text[], 'Chung cư mini 24 căn hộ, tối ưu diện tích cho thuê và hệ thống PCCC theo quy chuẩn mới.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/59.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/59.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/60.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/57.jpg']::text[], null, false, 'published', '2023-06-17T00:00:00.000Z'),
  ('prj-018', 'giam-sat-hoan-thien-vinhomes-vu-yen', 'Giám sát hoàn thiện Vinhomes Vũ Yên', 'residential', 'Vũ Yên, Hải Phòng', 'Biệt thự đảo', 900, 2026, null, array['Giám sát']::text[], 'Giám sát thi công hoàn thiện kiến trúc và nội thất các căn biệt thự tại Vinhomes Royal Island.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/45.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/45.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/42.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/44.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/43.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/46.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/47.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/41.jpg']::text[], null, false, 'published', '2026-06-18T00:00:00.000Z'),
  ('prj-019', 'noi-that-nha-pho-anh-manh', 'Nội thất nhà phố anh Mạnh', 'interior', 'TP. Bắc Giang', '4 tầng · 320 m² sàn', 320, 2025, null, array['Thiết kế', 'Sản xuất', 'Thi công']::text[], 'Nội thất hiện đại tông ấm, toàn bộ đồ gỗ sản xuất tại xưởng Anyhome theo kích thước riêng.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/29.jpg', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/29.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/37.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/38.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/40.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/26.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/24.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/25.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/28.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/22.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/23.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/21.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/19.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/33.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/34.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/35.jpg', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/36.jpg']::text[], null, true, 'published', '2025-06-19T00:00:00.000Z'),
  ('prj-020', 'nha-hang-cafe-2-tang-mang-den', 'Nhà hàng café 2 tầng Măng Đen', 'interior', 'Khu du lịch Măng Đen, Kon Tum', '2 tầng · 400 m² sàn', 400, 2024, null, array['Thiết kế', 'Thi công']::text[], 'Không gian café – nhà hàng giữa rừng thông, vật liệu gỗ thông và kính lớn đón sương.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/logo.png', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/logo.png']::text[], null, false, 'draft', '2024-06-20T00:00:00.000Z'),
  ('prj-021', 'quan-cafe-3-tang-da-nang', 'Quán café 3 tầng Đà Nẵng', 'interior', 'TP. Đà Nẵng', '3 tầng · 360 m² sàn', 360, 2024, null, array['Thiết kế', 'Thi công']::text[], 'Café phong cách industrial – tropical, sân thượng mở và quầy bar trung tâm.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/logo.png', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/logo.png']::text[], null, false, 'draft', '2024-06-21T00:00:00.000Z'),
  ('prj-022', 'can-ho-cao-cap-phong-cach-japandi', 'Căn hộ cao cấp phong cách Japandi', 'interior', 'Hà Nội', 'Căn hộ · 135 m²', 135, 2026, null, array['Thiết kế', 'Sản xuất', 'Thi công']::text[], 'Căn hộ 3 phòng ngủ tối giản Japandi với gỗ sồi sáng màu và ánh sáng gián tiếp.', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/logo.png', array['https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/logo.png']::text[], null, true, 'draft', '2026-06-22T00:00:00.000Z')
on conflict (id) do update set slug = excluded.slug, title = excluded.title, category = excluded.category, location = excluded.location, scale = excluded.scale, area = excluded.area, year = excluded.year, client = excluded.client, scope = excluded.scope, summary = excluded.summary, cover = excluded.cover, gallery = excluded.gallery, before_after = excluded.before_after, featured = excluded.featured, status = excluded.status, created_at = excluded.created_at;

insert into public.posts (id, slug, title, excerpt, content, cover, category, tags, author, status, published_at, updated_at) values
  ('post-001', 'design-and-build-giai-phap-tron-goi', 'Design & Build: vì sao chủ đầu tư nên chọn một đầu mối từ thiết kế đến thi công?', 'Mô hình tổng thầu Design & Build giúp hạn chế sai lệch giữa bản vẽ và thực tế, tối ưu chi phí và kiểm soát tiến độ.', '<p>Khi thiết kế và thi công do hai đơn vị khác nhau đảm nhận, chủ đầu tư thường phải tự xử lý những xung đột giữa bản vẽ và hiện trường.</p><h2>3 lợi ích cốt lõi</h2><ul><li><strong>Một đầu mối chịu trách nhiệm</strong> cho toàn bộ chất lượng.</li><li><strong>Dự toán sát thực tế</strong> ngay từ giai đoạn ý tưởng.</li><li><strong>Rút ngắn tiến độ</strong> nhờ triển khai song song thiết kế – sản xuất.</li></ul><blockquote>Anyhome – Thiết kế khác biệt, kiến tạo không gian giá trị.</blockquote>', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/64.jpg', 'knowledge', array['Design & Build', 'Tư vấn']::text[], 'Phòng Thiết kế', 'published', '2026-08-12T02:00:00.000Z', '2026-08-12T02:00:00.000Z'),
  ('post-002', 'khoi-cong-nha-may-kintop', 'Khởi công nhà máy sản xuất thiết bị công nghiệp Kintop tại KCN Lai Cách', 'Anyhome chính thức triển khai thi công nhà xưởng 7.200 m² cho Công ty Kintop tại Cẩm Giàng, Hải Dương.', '<p>Sáng nay, Anyhome cùng chủ đầu tư tổ chức lễ khởi công nhà máy Kintop.</p><h2>Quy mô dự án</h2><p>Nhà xưởng kết cấu thép kết hợp bê tông cốt thép, trang bị cầu trục 10 tấn.</p>', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/15.jpg', 'construction-log', array['Công nghiệp', 'Khởi công']::text[], 'Ban Chỉ huy công trường', 'published', '2026-07-03T02:00:00.000Z', '2026-07-03T02:00:00.000Z'),
  ('post-003', 'xu-huong-noi-that-japandi-2026', 'Xu hướng nội thất Japandi 2026: tối giản, ấm áp và bền vững', 'Gỗ sáng màu, đường nét tối giản và ánh sáng gián tiếp — vì sao Japandi tiếp tục dẫn dắt nội thất căn hộ cao cấp.', '<p>Japandi là sự giao thoa giữa tinh thần wabi-sabi Nhật Bản và công năng Bắc Âu.</p>', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/28.jpg', 'knowledge', array['Nội thất', 'Xu hướng']::text[], 'Studio Nội thất', 'published', '2026-05-20T02:00:00.000Z', '2026-05-20T02:00:00.000Z'),
  ('post-004', 'tuyen-dung-ky-su-giam-sat', 'Tuyển dụng Kỹ sư giám sát xây dựng (Hà Nội, Hải Phòng)', 'Anyhome mở rộng đội ngũ, tuyển 05 kỹ sư giám sát dân dụng và công nghiệp.', '<p>Bản nháp — đang hoàn thiện mô tả công việc.</p>', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/65.jpg', 'recruitment', array['Tuyển dụng']::text[], 'Phòng Nhân sự', 'draft', null, '2026-09-28T02:00:00.000Z')
on conflict (id) do update set slug = excluded.slug, title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, cover = excluded.cover, category = excluded.category, tags = excluded.tags, author = excluded.author, status = excluded.status, published_at = excluded.published_at, updated_at = excluded.updated_at;

insert into public.equipments (id, name, "group", spec, quantity, unit, origin, image, created_at) values
  ('eq-1', 'Máy xúc bánh xích', 'machinery', 'Gầu 0,7 – 1,2 m³', 3, 'chiếc', 'Nhật Bản', '', '2024-01-01T00:00:00.000Z'),
  ('eq-2', 'Cần trục tháp', 'machinery', 'Sức nâng 6 – 8 tấn, tầm với 50 m', 2, 'bộ', 'Trung Quốc', '', '2024-01-01T00:00:01.000Z'),
  ('eq-3', 'Máy trộn & bơm bê tông', 'machinery', 'Công suất 30 – 60 m³/h', 4, 'bộ', 'Hàn Quốc', '', '2024-01-01T00:00:02.000Z'),
  ('eq-4', 'Máy đầm dùi, đầm bàn', 'machinery', '1,5 – 2,2 kW', 20, 'chiếc', 'Nhật Bản', '', '2024-01-01T00:00:03.000Z'),
  ('eq-5', 'Cốp pha nhôm định hình', 'formwork', 'Hệ sàn + vách, luân chuyển 200+ lần', 1800, 'm²', 'Việt Nam', '', '2024-01-01T00:00:04.000Z'),
  ('eq-6', 'Cốp pha thép & ván phủ phim', 'formwork', 'Dầm, cột, sàn', 2500, 'm²', 'Việt Nam', '', '2024-01-01T00:00:05.000Z'),
  ('eq-7', 'Giàn giáo nêm, giáo chống tổ hợp', 'formwork', 'Chiều cao lắp dựng tới 30 m', 3000, 'bộ', 'Việt Nam', 'https://xezsyblbczsbxzvrffut.supabase.co/storage/v1/object/public/uploads/anyhome/67.jpg', '2024-01-01T00:00:06.000Z'),
  ('eq-8', 'Máy toàn đạc điện tử', 'survey', 'Độ chính xác góc 2″', 2, 'bộ', 'Nhật Bản', '', '2024-01-01T00:00:07.000Z'),
  ('eq-9', 'Máy thủy bình, máy laser cân bằng', 'survey', 'Tự động cân bằng', 6, 'bộ', 'Đức', '', '2024-01-01T00:00:08.000Z'),
  ('eq-10', 'Máy siêu âm & súng bật nẩy bê tông', 'survey', 'Kiểm tra cường độ kết cấu', 2, 'bộ', 'Thụy Sĩ', '', '2024-01-01T00:00:09.000Z'),
  ('eq-11', 'Máy CNC cắt ván công nghiệp', 'workshop', 'Bàn làm việc 1.300 × 2.500 mm', 2, 'máy', 'Đài Loan', '', '2024-01-01T00:00:10.000Z'),
  ('eq-12', 'Máy dán cạnh tự động, khoan đa trục', 'workshop', 'Dây chuyền gia công tủ bếp, tủ áo', 3, 'máy', 'Đài Loan', '', '2024-01-01T00:00:11.000Z')
on conflict (id) do update set name = excluded.name, "group" = excluded."group", spec = excluded.spec, quantity = excluded.quantity, unit = excluded.unit, origin = excluded.origin, image = excluded.image, created_at = excluded.created_at;

insert into public.leads (id, name, phone, email, project_type, area, budget, message, status, created_at) values
  ('lead-001', 'Nguyễn Minh Tuấn', '0903 112 334', 'tuan.nm@example.com', 'residential', '320 m²', '3 – 5 tỷ', 'Cần thiết kế & thi công biệt thự 3 tầng tại Hà Đông.', 'new', '2026-10-07T01:15:00.000Z'),
  ('lead-002', 'Trần Thu Hà', '0987 556 102', null, 'interior', '110 m²', '500 tr – 1 tỷ', 'Nội thất căn hộ 3PN phong cách hiện đại.', 'new', '2026-10-06T07:15:00.000Z'),
  ('lead-003', 'Công ty TNHH Hưng Phát', '0912 889 001', 'contact@hungphat.example', 'industrial', '5.000 m²', 'Trên 20 tỷ', 'Nhà xưởng KCN Quế Võ, cần báo giá thiết kế – thi công.', 'contacted', '2026-10-04T03:15:00.000Z'),
  ('lead-004', 'Lê Văn Phúc', '0868 230 777', null, 'residential', '180 m²', null, 'Nhà phố 5 tầng mặt tiền 5 m.', 'quoted', '2026-10-01T09:15:00.000Z'),
  ('lead-005', 'Phạm Ngọc Anh', '0936 450 218', null, 'interior', null, '1 – 3 tỷ', 'Showroom thời trang 2 tầng.', 'closed', '2026-09-25T04:15:00.000Z')
on conflict (id) do update set name = excluded.name, phone = excluded.phone, email = excluded.email, project_type = excluded.project_type, area = excluded.area, budget = excluded.budget, message = excluded.message, status = excluded.status, created_at = excluded.created_at;

insert into public.site_settings (id, hotline, hotline2, zalo, email, website, hq_address, office_address, branch_address, map_query, stats, profile_pdf_url, profile_downloads) values
  (1, '0912 623 887', '0931 421 989', '0912623887', 'thietkeanyhome@gmail.com', 'www.anyhome.com.vn', 'Số 5, ngõ 45/52, đường Cầu Cốc, Phường Tây Mỗ, TP Hà Nội', 'Tầng 2, Tòa nhà số 385 Trần Đại Nghĩa, Hà Nội', 'Vinhomes Royal Island, Đảo Hoàng Gia, Phường Thuỷ Nguyên, Hải Phòng', '385 Trần Đại Nghĩa, Hai Bà Trưng, Hà Nội', '[{"label":"Năm kinh nghiệm","value":5,"suffix":"+"},{"label":"Công trình hoàn thành","value":500,"suffix":"+"},{"label":"Tỉnh thành phủ sóng","value":20,"suffix":""},{"label":"m² sàn đã thi công","value":250000,"suffix":"+"}]'::jsonb, 'https://cdnm.heyzine.com/files/uploaded/v3/908b04446750c12b1e752a3ad0883d7ee4564355.pdf', 1284)
on conflict (id) do nothing;

commit;
